name: Workflow reusing
on: 
  workflow_dispatch:
    inputs:
      java_version:
        default: "17"
        description: java_ver
        type: choice
        options:
          - "17"
          - "18"
          - "20"
          - "21"
env:
  java_version: ${{ inputs.java_version }}
permissions:
  contents: read
  id-token: write
jobs:
  build:
    uses: Apswara/gh-actions/.github/workflows/reuseable.yaml@main
    with:
      java_ver:  ${{ inputs.java_version }}
